version: '3'
services:
  api:
      build: ./api
      command: npm run start
      volumes:
        - ./api:/usr/app/api
        - /usr/app/api/node_modules
      ports:
        - "3000:3000"
      depends_on:
        - dbpostgres
      links:
        - "dbpostgres"
      environment:
        DB_PORT: 5432
        DB_USER: phonelist
        DB_PASSWORD: ASD12asd
        DATABASE: phonelist
  dbpostgres:
    image: postgres
    restart: always
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: phonelist
      POSTGRES_PASSWORD: ASD12asd
      POSTGRES_DB: phonelist