version: '3'
services:
  dbpostgres:
    image: postgres
    restart: always
    volumes:
      - ./postgresql_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: ASD12asd
      POSTGRES_DB: phonelist